### ISSUE TITLE
Create private channel

### ISSUE THREAD

**Issue by daniel-chris-lucas** [restcord/restcord#104]
I'm trying to create private channels. Currently, I have managed to create voice channels, but all users on the server are able to see and join the channels. How can I make the channels so they are only available when invited ?

My current test code is :

```
$discord = new \RestCord\DiscordClient(['token' => config('services.discord.bot_token')]);
$channel = $discord->guild->createGuildChannel([
    'guild.id'              => config('services.discord.guild_id'),
    'name'                  => 'lobby_' . uniqid(),
    'type'                  => 2, // Voice
    'permission_overwrites' => [
     ],
]);
$invitation = $discord->channel->createChannelInvite([
    'channel.id' => $channel->id,
]);

return "https://discordapp.com/invite/{$invitation->code}";
```

Thanks in advance, any help is much appreciated

**Comment by oliverschloebe** [comment]
AFAIK there's no permission option available making a channel visible to invited users only.

Instead, I guess you will need to work with Role permissions so that only users with a certain role can see the hidden channel.

When creating the Channel, `permission_overwrites` holds custom permissions for the channel which should allow you to make the channel visible for a certain Role only.

https://discordapp.com/developers/docs/topics/permissions

**Comment by cryptiklemur** [comment]
You can set up permission_overwrites with `user`s as well as roles

**Comment by bqobd** [comment]
Can you please give us an example for "permission_overwrites".. i cant get it to work?
